
import React, { useState, useRef, useEffect } from 'react';
import { diagnoseCrop } from '../services/geminiService';
import { Camera, Upload, Loader2, CheckCircle2, AlertCircle, Info, X, Zap, RotateCw, Disc, IndianRupee, Share2, Copy, Check } from 'lucide-react';
import { Language } from '../types';

const CropDoctor: React.FC<{ lang: Language }> = ({ lang }) => {
  const [isLiveMode, setIsLiveMode] = useState(false);
  const [image, setImage] = useState<string | null>(null);
  const [diagnosis, setDiagnosis] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [cameraPermission, setCameraPermission] = useState<'prompt' | 'granted' | 'denied'>('prompt');
  const [isFlashActive, setIsFlashActive] = useState(false);
  const [isShared, setIsShared] = useState(false);
  
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const isHindi = lang === Language.HINDI;

  const startCamera = async () => {
    setIsLiveMode(true);
    setDiagnosis(null);
    setImage(null);
    setCameraPermission('prompt');
    
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ 
        video: { 
          facingMode: 'environment',
          width: { ideal: 1920 },
          height: { ideal: 1080 }
        },
        audio: false
      });
      
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.onloadedmetadata = () => {
          videoRef.current?.play().catch(e => console.error("Video play error:", e));
        };
        setCameraPermission('granted');
      }
    } catch (err) {
      console.error("Camera access error:", err);
      setCameraPermission('denied');
      setIsLiveMode(false);
    }
  };

  const stopCamera = () => {
    if (videoRef.current?.srcObject) {
      const stream = videoRef.current.srcObject as MediaStream;
      stream.getTracks().forEach(track => track.stop());
      videoRef.current.srcObject = null;
    }
    setIsLiveMode(false);
  };

  const capturePhoto = () => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    
    if (!video || !canvas || video.readyState < 2) {
      console.warn("Capture failed: Video not ready");
      return;
    }

    setIsFlashActive(true);
    setTimeout(() => setIsFlashActive(false), 150);

    const ctx = canvas.getContext('2d');
    if (ctx) {
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      
      const dataUrl = canvas.toDataURL('image/jpeg', 0.92);
      if (dataUrl && dataUrl.length > 500) {
        setImage(dataUrl);
        stopCamera();
        runDiagnosis(dataUrl);
      }
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const dataUrl = reader.result as string;
        setImage(dataUrl);
        runDiagnosis(dataUrl);
      };
      reader.readAsDataURL(file);
    }
  };

  const runDiagnosis = async (imgData: string) => {
    setIsLoading(true);
    setDiagnosis(null);
    try {
      const base64 = imgData.split(',')[1];
      const result = await diagnoseCrop(base64, lang);
      setDiagnosis(result);
    } catch (e) {
      console.error("AI Diagnosis Error:", e);
      setDiagnosis({ 
        error: true, 
        problemName: isHindi ? "त्रुटि" : "Error", 
        diagnosis: isHindi ? "AI विश्लेषण विफल रहा। कृपया फिर से प्रयास करें।" : "AI Analysis failed. Please try again." 
      });
    } finally {
      setIsLoading(false);
    }
  };

  const shareDiagnosis = async () => {
    if (!diagnosis) return;

    const shareTitle = isHindi ? `KisanAI फसल रिपोर्ट: ${diagnosis.problemName}` : `KisanAI Crop Report: ${diagnosis.problemName}`;
    const shareText = `
${isHindi ? '--- फसल निदान रिपोर्ट ---' : '--- Crop Diagnosis Report ---'}
${isHindi ? 'समस्या' : 'Problem'}: ${diagnosis.problemName}
${isHindi ? 'विवरण' : 'Details'}: ${diagnosis.diagnosis}

${isHindi ? 'जैविक समाधान' : 'Organic Solution'}: ${diagnosis.solutionOrganic}
${isHindi ? 'रासायनिक समाधान' : 'Chemical Solution'}: ${diagnosis.solutionChemical}

${isHindi ? 'बचाव के टिप्स' : 'Prevention Tips'}: ${diagnosis.preventionTips}

${isHindi ? 'KisanAI द्वारा जनरेट किया गया' : 'Generated by KisanAI'}
    `.trim();

    if (navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: window.location.href
        });
      } catch (err) {
        console.error("Error sharing:", err);
      }
    } else {
      // Fallback to clipboard
      try {
        await navigator.clipboard.writeText(shareText);
        setIsShared(true);
        setTimeout(() => setIsShared(false), 2000);
      } catch (err) {
        console.error("Clipboard error:", err);
      }
    }
  };

  return (
    <div className="space-y-6 font-['Outfit'] pb-24">
      <div className="bg-white p-6 md:p-8 rounded-[2.5rem] shadow-xl border border-green-100 relative overflow-hidden">
        <div className="relative z-10">
          <h2 className="text-3xl font-black mb-1 flex items-center gap-3 tracking-tighter">
            <div className="p-3 bg-green-600 rounded-2xl text-white shadow-lg shadow-green-200">
               <Camera className="w-6 h-6" />
            </div>
            {isHindi ? 'फसल डॉक्टर' : 'AI Crop Doctor'}
          </h2>
          <p className="text-slate-400 text-sm font-bold uppercase tracking-widest mt-2">
            {isHindi ? 'बीमारी का पता लगाने के लिए फोटो लें' : 'Diagnose pests and diseases instantly'}
          </p>
        </div>
        <Zap className="absolute -right-4 -bottom-4 w-32 h-32 text-green-50 opacity-20 rotate-12" />
      </div>

      <div className="relative bg-slate-900 rounded-[3rem] shadow-2xl border-8 border-white overflow-hidden aspect-[3/4] md:aspect-video flex items-center justify-center">
        {isLiveMode ? (
          <>
            <video ref={videoRef} autoPlay playsInline muted className="w-full h-full object-cover" />
            {isFlashActive && <div className="absolute inset-0 bg-white z-50 transition-opacity"></div>}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
               <div className="w-72 h-72 border-2 border-white/20 rounded-[3rem] relative">
                  <div className="absolute top-0 left-0 w-12 h-12 border-t-4 border-l-4 border-green-500 rounded-tl-3xl"></div>
                  <div className="absolute top-0 right-0 w-12 h-12 border-t-4 border-r-4 border-green-500 rounded-tr-3xl"></div>
                  <div className="absolute bottom-0 left-0 w-12 h-12 border-b-4 border-l-4 border-green-500 rounded-bl-3xl"></div>
                  <div className="absolute bottom-0 right-0 w-12 h-12 border-b-4 border-r-4 border-green-500 rounded-br-3xl"></div>
               </div>
            </div>
            <div className="absolute bottom-0 left-0 right-0 p-10 bg-gradient-to-t from-black/80 to-transparent flex items-center justify-between">
               <button onClick={stopCamera} className="p-5 bg-white/10 backdrop-blur-xl rounded-3xl text-white border border-white/10 active:scale-90 transition-all">
                 <X className="w-7 h-7" />
               </button>
               <div className="flex flex-col items-center gap-3">
                 <button 
                   onClick={capturePhoto}
                   className="w-24 h-24 bg-white rounded-full flex items-center justify-center shadow-2xl active:scale-90 transition-transform p-2 group"
                 >
                   <div className="w-full h-full bg-green-600 rounded-full flex items-center justify-center group-hover:bg-green-500 transition-colors">
                     <Camera className="w-10 h-10 text-white" />
                   </div>
                 </button>
                 <span className="text-[10px] font-black text-white uppercase tracking-[0.2em]">{isHindi ? 'फोटो लें' : 'Take Photo'}</span>
               </div>
               <div className="w-14"></div>
            </div>
          </>
        ) : image ? (
          <div className="absolute inset-0 bg-slate-900 flex items-center justify-center">
             <img src={image} className="max-h-full max-w-full object-contain animate-in zoom-in-95 duration-300" alt="Captured Crop" />
             <div className="absolute top-8 right-8 flex gap-4">
                <button 
                  onClick={() => { setImage(null); setDiagnosis(null); }}
                  className="bg-black/60 backdrop-blur-xl text-white p-4 rounded-2xl hover:bg-black transition-all shadow-xl"
                >
                  <X className="w-6 h-6" />
                </button>
             </div>
          </div>
        ) : (
          <div className="text-center p-12 space-y-10">
            <div className="w-24 h-24 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto shadow-inner relative group cursor-pointer" onClick={startCamera}>
               <Camera className="w-12 h-12 group-hover:scale-110 transition-transform" />
               <div className="absolute inset-0 bg-green-600/10 rounded-full animate-ping"></div>
            </div>
            <div className="space-y-6">
              <button 
                onClick={startCamera}
                className="w-full bg-green-600 text-white py-6 px-12 rounded-[2rem] font-black text-xl shadow-2xl shadow-green-900/40 active:scale-95 transition-all flex items-center justify-center gap-4 hover:bg-green-700"
              >
                <Camera className="w-8 h-8" /> {isHindi ? 'कैमरा शुरू करें' : 'Launch AI Camera'}
              </button>
              <button 
                onClick={() => fileInputRef.current?.click()}
                className="w-full bg-white/5 text-white/60 py-4 rounded-[1.5rem] font-black text-sm border border-white/10 flex items-center justify-center gap-3 hover:bg-white/10 hover:text-white transition-all"
              >
                <Upload className="w-5 h-5" /> {isHindi ? 'गैलरी से फोटो चुनें' : 'Upload Existing Photo'}
              </button>
            </div>
          </div>
        )}
      </div>

      <input type="file" ref={fileInputRef} onChange={handleFileUpload} className="hidden" accept="image/*" />
      <canvas ref={canvasRef} className="hidden" />

      {isLoading && (
        <div className="bg-white p-12 rounded-[3rem] shadow-2xl flex flex-col items-center gap-8 animate-in slide-in-from-bottom-10">
           <div className="relative">
              <Loader2 className="w-20 h-20 text-green-600 animate-spin" />
              <Zap className="absolute inset-0 m-auto w-8 h-8 text-green-400" />
           </div>
           <div className="text-center space-y-2">
              <p className="text-2xl font-black text-slate-800">{isHindi ? 'AI विश्लेषण कर रहा है...' : 'AI is Analyzing...'}</p>
              <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">Finding the best organic & chemical solutions</p>
           </div>
        </div>
      )}

      {diagnosis && !isLoading && (
        <div className="bg-white rounded-[3rem] shadow-2xl border border-green-50 overflow-hidden animate-in slide-in-from-bottom-10">
          <div className={`${diagnosis.error ? 'bg-slate-700' : 'bg-gradient-to-r from-red-600 to-red-500'} p-10 text-white relative`}>
             <div className="relative z-10">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-3 opacity-80">
                     <AlertCircle className="w-5 h-5" />
                     <span className="text-xs font-black uppercase tracking-[0.2em]">{isHindi ? 'निदान रिपोर्ट' : 'Diagnosis Report'}</span>
                  </div>
                  <button 
                    onClick={shareDiagnosis}
                    className="flex items-center gap-2 bg-white/20 hover:bg-white/30 px-5 py-2.5 rounded-2xl font-black text-xs uppercase tracking-widest backdrop-blur-md transition-all active:scale-90"
                  >
                    {isShared ? <Check className="w-4 h-4 text-green-300" /> : <Share2 className="w-4 h-4" />}
                    {isShared ? (isHindi ? 'कॉपी हो गया' : 'Copied') : (isHindi ? 'रिपोर्ट साझा करें' : 'Share Report')}
                  </button>
                </div>
                <h3 className="text-4xl font-black mb-3 tracking-tighter leading-tight">{diagnosis.problemName}</h3>
                <p className="text-xl opacity-95 font-medium leading-relaxed">{diagnosis.diagnosis}</p>
             </div>
             <Disc className="absolute -right-10 -bottom-10 w-48 h-48 text-white/10 animate-spin-slow" />
          </div>
          
          {!diagnosis.error && (
            <div className="p-10 grid grid-cols-1 md:grid-cols-2 gap-10">
              <div className="space-y-8">
                <div className="p-8 bg-emerald-50 rounded-[2.5rem] border border-emerald-100 flex gap-5 group hover:bg-emerald-100 transition-colors">
                   <div className="p-4 bg-white rounded-2xl shadow-sm h-fit"><CheckCircle2 className="w-8 h-8 text-emerald-600" /></div>
                   <div>
                      <h4 className="font-black text-emerald-900 text-xl mb-2">{isHindi ? 'जैविक समाधान' : 'Organic Solution'}</h4>
                      <p className="text-emerald-800 text-lg leading-relaxed font-medium">{diagnosis.solutionOrganic}</p>
                   </div>
                </div>
                <div className="p-8 bg-amber-50 rounded-[2.5rem] border border-amber-100 flex gap-5 group hover:bg-amber-100 transition-colors">
                   <div className="p-4 bg-white rounded-2xl shadow-sm h-fit"><AlertCircle className="w-8 h-8 text-amber-600" /></div>
                   <div>
                      <h4 className="font-black text-amber-900 text-xl mb-2">{isHindi ? 'रासायनिक समाधान' : 'Chemical Solution'}</h4>
                      <p className="text-amber-800 text-lg leading-relaxed font-medium">{diagnosis.solutionChemical}</p>
                   </div>
                </div>
              </div>
              
              <div className="space-y-8">
                 <div className="p-8 bg-slate-900 rounded-[2.5rem] text-white shadow-xl shadow-slate-200">
                    <p className="text-xs font-black text-slate-400 uppercase tracking-widest mb-2">{isHindi ? 'अनुमानित लागत' : 'Estimated Cost Range'}</p>
                    <p className="text-5xl font-black tracking-tighter flex items-center gap-3">
                       <IndianRupee className="w-10 h-10 text-green-500" />
                       {diagnosis.estimatedCostRange}
                    </p>
                 </div>
                 <div className="p-8 bg-green-50 rounded-[2.5rem] border border-green-100">
                    <h4 className="font-black text-green-900 text-xl mb-4 flex items-center gap-2">
                       <Info className="w-6 h-6 text-blue-500" />
                       {isHindi ? 'बचाव के टिप्स' : 'Prevention Tips'}
                    </h4>
                    <p className="text-green-800 text-lg font-medium leading-relaxed">{diagnosis.preventionTips}</p>
                 </div>
              </div>
            </div>
          )}
          
          <div className="p-6 flex flex-col md:flex-row gap-4 border-t border-slate-100">
            <button 
              onClick={() => { setImage(null); setDiagnosis(null); }}
              className="flex-1 bg-slate-100 py-6 rounded-3xl font-black uppercase tracking-[0.2em] text-sm hover:bg-slate-200 transition-all"
            >
              {isHindi ? 'नई जांच' : 'New Analysis'}
            </button>
            <button 
              onClick={shareDiagnosis}
              className="flex-1 bg-green-600 text-white py-6 rounded-3xl font-black uppercase tracking-[0.2em] text-sm hover:bg-green-700 transition-all flex items-center justify-center gap-3"
            >
              <Share2 className="w-5 h-5" />
              {isHindi ? 'शेयर करें' : 'Share Result'}
            </button>
          </div>
        </div>
      )}
      
      <style>{`
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .animate-spin-slow {
          animation: spin-slow 20s linear infinite;
        }
      `}</style>
    </div>
  );
};

export default CropDoctor;
